################################################################################
# Forest Plots for Genetic Literacy Predictors
# 
# Description: Creates forest plots showing standardized regression coefficients
#              for predictors of three genetic literacy outcomes:
#              1. Familiarity/Subjective Knowledge (1-7 scale)
#              2. Knowledge/Objective Knowledge (0-17 scale)  
#              3. Skills/Knowledge Comprehension (0-6 scale)
# Code generated by Claude; please reference Claudev4.1 Opus, Anthropic
# Author: [Your Name]
# Date: September 2025
# R Version: [Your R Version]
#
# Required packages: ggplot2, dplyr, tidyr, gridExtra
#
# Data: N = 4,056 participants from SPARK and general population cohorts
################################################################################

# Load required libraries ------------------------------------------------------
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)

# Set theme for publication-quality plots -------------------------------------
theme_set(theme_minimal(base_size = 12))

# Define color scheme for significance levels ---------------------------------
sig_colors <- c(
  "***" = "#d73027",  # Dark red for p < 0.001
  "**" = "#f46d43",   # Orange for p < 0.01
  "*" = "#fdae61",    # Yellow for p < 0.05
  "n.s." = "#abd9e9"  # Light blue for non-significant
)

# Create data frames for each outcome -----------------------------------------

# Familiarity/Subjective Knowledge data
familiarity_data <- data.frame(
  variable = factor(c(
    "Population",
    "Education: High School",
    "Education: Undergraduate",
    "Education: Graduate",
    "Genetic Knowledge Confidence",
    "Perceived Importance",
    "Liberal",
    "Conservative",
    "Prefer not to answer",
    "Religious, not actively practicing",
    "Religious, actively practicing"
  ), levels = rev(c(
    "Population",
    "Education: High School",
    "Education: Undergraduate",
    "Education: Graduate",
    "Genetic Knowledge Confidence",
    "Perceived Importance",
    "Liberal",
    "Conservative",
    "Prefer not to answer",
    "Religious, not actively practicing",
    "Religious, actively practicing"
  ))),
  coefficient = c(0.207, 0.367, 0.528, 0.620, 0.491, 0.073, 0.145, 0.031, -0.139, -0.055, -0.189),
  lower_ci = c(0.150, 0.160, 0.320, 0.409, 0.457, 0.056, 0.080, -0.039, -0.256, -0.122, -0.255),
  upper_ci = c(0.265, 0.574, 0.735, 0.832, 0.526, 0.091, 0.210, 0.101, -0.022, 0.012, -0.123),
  significance = factor(c("***", "***", "***", "***", "***", "***", "***", "n.s.", "*", "n.s.", "***"),
                        levels = c("***", "**", "*", "n.s."))
)

# Knowledge/Objective Knowledge data
knowledge_data <- data.frame(
  variable = factor(c(
    "Population",
    "Education: High School",
    "Education: Undergraduate",
    "Education: Graduate",
    "Genetic Knowledge Confidence",
    "Perceived Importance",
    "Liberal",
    "Conservative",
    "Prefer not to answer",
    "Religious, not actively practicing",
    "Religious, actively practicing"
  ), levels = rev(c(
    "Population",
    "Education: High School",
    "Education: Undergraduate",
    "Education: Graduate",
    "Genetic Knowledge Confidence",
    "Perceived Importance",
    "Liberal",
    "Conservative",
    "Prefer not to answer",
    "Religious, not actively practicing",
    "Religious, actively practicing"
  ))),
  coefficient = c(0.344, 0.125, 0.351, 0.558, 0.395, 0.024, 0.140, 0.105, -0.228, -0.116, -0.188),
  lower_ci = c(0.284, -0.089, 0.136, 0.340, 0.358, 0.005, 0.073, 0.033, -0.348, -0.185, -0.256),
  upper_ci = c(0.403, 0.339, 0.565, 0.777, 0.431, 0.042, 0.207, 0.177, -0.107, -0.046, -0.119),
  significance = factor(c("***", "n.s.", "**", "***", "***", "*", "***", "**", "***", "**", "***"),
                        levels = c("***", "**", "*", "n.s."))
)

# Skills/Knowledge Comprehension data
skills_data <- data.frame(
  variable = factor(c(
    "Population",
    "Education: High School",
    "Education: Undergraduate",
    "Education: Graduate",
    "Genetic Knowledge Confidence",
    "Perceived Importance",
    "Liberal",
    "Conservative",
    "Prefer not to answer",
    "Religious, not actively practicing",
    "Religious, actively practicing"
  ), levels = rev(c(
    "Population",
    "Education: High School",
    "Education: Undergraduate",
    "Education: Graduate",
    "Genetic Knowledge Confidence",
    "Perceived Importance",
    "Liberal",
    "Conservative",
    "Prefer not to answer",
    "Religious, not actively practicing",
    "Religious, actively practicing"
  ))),
  coefficient = c(0.472, 0.235, 0.401, 0.479, 0.154, 0.026, 0.155, 0.007, -0.199, -0.024, -0.113),
  lower_ci = c(0.408, 0.006, 0.171, 0.245, 0.116, 0.007, 0.083, -0.070, -0.328, -0.098, -0.186),
  upper_ci = c(0.536, 0.464, 0.630, 0.712, 0.193, 0.046, 0.227, 0.084, -0.070, 0.050, -0.040),
  significance = factor(c("***", "*", "***", "***", "***", "**", "***", "n.s.", "**", "n.s.", "**"),
                        levels = c("***", "**", "*", "n.s."))
)

# Function to create forest plot ----------------------------------------------
create_forest_plot <- function(data, title, subtitle) {
  
  # Add separator lines positions
  separator_positions <- c(7.5, 5.5, 2.5)  # Between variable groups
  
  p <- ggplot(data, aes(x = coefficient, y = variable)) +
    # Add vertical reference line at 0
    geom_vline(xintercept = 0, linetype = "dashed", color = "gray40", size = 0.8) +
    
    # Add horizontal separator lines
    geom_hline(yintercept = separator_positions, 
               color = "gray80", size = 0.5, alpha = 0.5) +
    
    # Add confidence intervals
    geom_errorbarh(aes(xmin = lower_ci, xmax = upper_ci, color = significance), 
                   height = 0, size = 1.2) +
    
    # Add point estimates
    geom_point(aes(color = significance), size = 3.5) +
    
    # Add coefficient values as text
    geom_text(aes(label = sprintf("%.3f", coefficient)), 
              vjust = -1, size = 3, fontface = "bold") +
    
    # Add significance stars
    geom_text(aes(label = as.character(significance)), 
              vjust = 2, size = 3.5, fontface = "bold") +
    
    # Set color scale
    scale_color_manual(values = sig_colors,
                      name = "Significance",
                      labels = c("p < 0.001", "p < 0.01", "p < 0.05", "Not significant"),
                      drop = FALSE) +
    
    # Set x-axis limits and labels
    scale_x_continuous(limits = c(-0.4, 1.0),
                      breaks = seq(-0.4, 1.0, by = 0.2),
                      name = "Standardized Coefficient") +
    
    # Customize theme
    theme(
      plot.title = element_text(hjust = 0.5, size = 16, face = "bold"),
      plot.subtitle = element_text(hjust = 0.5, size = 12, color = "gray40"),
      axis.title.y = element_blank(),
      axis.text.y = element_text(size = 11, hjust = 1),
      axis.title.x = element_text(size = 12, face = "bold"),
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank(),
      panel.border = element_rect(color = "gray80", fill = NA),
      legend.position = "bottom",
      legend.title = element_text(size = 11, face = "bold"),
      legend.text = element_text(size = 10),
      plot.margin = unit(c(1, 1, 1, 1), "cm")
    ) +
    
    # Add title and subtitle
    labs(
      title = title,
      subtitle = subtitle,
      caption = "N = 4,056 | Error bars represent 95% confidence intervals"
    )
  
  return(p)
}

# Create individual forest plots -----------------------------------------------

# Plot 1: Familiarity
plot_familiarity <- create_forest_plot(
  familiarity_data,
  "Familiarity/Subjective Knowledge",
  "(1-7 scale)"
)

# Plot 2: Knowledge
plot_knowledge <- create_forest_plot(
  knowledge_data,
  "Knowledge/Objective Knowledge",
  "(0-17 scale)"
)

# Plot 3: Skills
plot_skills <- create_forest_plot(
  skills_data,
  "Skills/Knowledge Comprehension",
  "(0-6 scale)"
)

# Display plots ----------------------------------------------------------------
print(plot_familiarity)
print(plot_knowledge)
print(plot_skills)

# Save individual plots to files -----------------------------------------------
ggsave("forest_plot_familiarity.png", plot_familiarity, 
       width = 10, height = 8, dpi = 300, bg = "white")
ggsave("forest_plot_knowledge.png", plot_knowledge, 
       width = 10, height = 8, dpi = 300, bg = "white")
ggsave("forest_plot_skills.png", plot_skills, 
       width = 10, height = 8, dpi = 300, bg = "white")

# Create combined plot for paper -----------------------------------------------
combined_plot <- grid.arrange(
  plot_familiarity, 
  plot_knowledge, 
  plot_skills,
  ncol = 1,
  nrow = 3,
  top = textGrob("Regression Analysis: Predictors of Genetic Literacy", 
                 gp = gpar(fontsize = 18, fontface = "bold"))
)

# Save combined plot
ggsave("forest_plots_combined.png", combined_plot, 
       width = 12, height = 20, dpi = 300, bg = "white")

# Save as PDF for publication
ggsave("forest_plots_combined.pdf", combined_plot, 
       width = 12, height = 20, device = "pdf")

# Print summary statistics -----------------------------------------------------
cat("\n========== STANDARDIZED COEFFICIENTS SUMMARY ==========\n")
cat("\nFamiliarity/Subjective Knowledge:\n")
print(familiarity_data[, c("variable", "coefficient", "significance")])

cat("\nKnowledge/Objective Knowledge:\n")
print(knowledge_data[, c("variable", "coefficient", "significance")])

cat("\nSkills/Knowledge Comprehension:\n")
print(skills_data[, c("variable", "coefficient", "significance")])

# Export data for supplementary materials -------------------------------------
write.csv(familiarity_data, "familiarity_coefficients.csv", row.names = FALSE)
write.csv(knowledge_data, "knowledge_coefficients.csv", row.names = FALSE)
write.csv(skills_data, "skills_coefficients.csv", row.names = FALSE)

# Session info for reproducibility --------------------------------------------
cat("\n========== SESSION INFO ==========\n")
sessionInfo()